<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title>Simplest CMS</title>
    <link rel="stylesheet" href="<?php echo $this->basePath?>/css/style1.css" type="text/css" media="screen" charset="utf-8" />
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <div class="wrapper">
        <h1 id="head">Simplest CMS</h1>
        <ul id="navigation">
            <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
            <li><a href="<?php echo $this->url('album') ?>"><?php echo $this->translate('Album') ?></a></li>
            <li><a href="<?php echo $this->url('fmi') ?>"><?php echo $this->translate('Fmi') ?></a></li>
            <li><a href="<?php echo $this->url('fmi/default', array('controller' => 'rangel', 'action'=>'index')) ?>"><?php echo $this->translate('Fmi/Rangel') ?></a></li>
            <li><a href="<?php echo $this->url('application/default', array('controller' => 'randjo', 'action' => 'index')) ?>"><?php echo $this->translate('App/Randjo') ?></a></li>
            <li><a href="https://plus.google.com/109784004571604738209/posts" target="_blank">Contact Admin</a></li>
            <li id="alignLeft"><a href="<?php echo $this->url('auth/default', array('controller' => 'index', 'action' => 'login')) ?>"><?php echo $this->translate('Login') ?></a></li>
            <li id="alignLeft"><a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 'action' => 'index')) ?>"><?php echo $this->translate('Register') ?></a></li>
        </ul>
      
        <?php echo $this->content;?>
    </div>
    <footer>
        <p>
            &#169; <a href="https://plus.google.com/109784004571604738209/posts" target="_blank">Rangel Marinov</a> <?php echo date('Y'); ?>
        </p>
    </footer>
  </body>
</html>   